### ISSUE TITLE
Adapt for non-subzero cases

### ISSUE THREAD

**Issue by olivierdalang** [raphiniert-com/ra-data-postgrest#10]
Hi !

I've set up a postgrest API following [their tutorial](http://postgrest.org/en/v7.0.0/tutorials/tut1.html). It works surprisingly well, but is not fully compatible with the authProvider in this repo, as the subzero starterkit does things slightly differently than vanilla postgrest :

- The auth endpoint is the same as the data endpoint (e.g. `api.example.com/rpc/login` instead of `/rest/rpc/login`).
- The login endpoint response is different (`/me` dict with user information for subzero, `{token: "xxx.yyy.zzz"}` for vanilla postgrest). It is possible to get user information by decoding the token client side. So it's a matter of storing the token (for reuse in the restProvider) and decoding the token client side (for use in getPermissions).

In the readme, you say you're open to contribution from that. How would you see that ? An alternative authProvider, or some settings/callbacks to customize behaviour ?

**Comment by scheiblr** [comment]
Hey, thanks for attacking this issue. I think a second authProvider would probably be the easiest way to get things running without breaking something. I would also like to add support for the [postgrest-starter kit](https://github.com/subzerocloud/postgrest-starter-kit) besides to vanilla (and maybe very customized) postgrest. So my suggestion: first writing additional authProvider and then let's see if we can abstract it into one. what do you think? If you already have an idea to abstract it right away, share it and we can face it ;)

**Comment by scheiblr** [comment]
Close due to inactivity
