### ISSUE TITLE
support specifying nullsfirst or nullslast in sorting config.

### ISSUE THREAD

**Issue by kav** [raphiniert-com/ra-data-postgrest#124]
I'm not sure the optimal path here as it may vary by field and table. Any thoughts on how granular to get here? I'm thinking something similar to defaultOp but we could get fancier with per table or field configuration.  For my specific use case I'd like to always use `nullslast` which would work with a single bool but I suspect that's not enough for others.

**Comment by scheiblr** [comment]
Thanks for coming up with this request. I think fine granular might be the optimum, but nevertheless, we might just start with your case and see if there is even the requirement for more. If so, in a next step we could make it more complex. Do you have a pull request for this issue?
