### ISSUE TITLE
Bad Request response when calling `getMany` with an empty array of ids

### ISSUE THREAD

**Issue by fzaninotto** [raphiniert-com/ra-data-postgrest#158]
## Problem

The `getMany` implementation generates a malformed URL when the `ids` parameter is an empty array:

```
dataProvider.getMany('tags', { ids: [] });
// GET http://127.0.0.1:54321/rest/v1/tags?id=eq.
```

Postgrest replies to this request with a `400 Bad Request` response.

## Analysis

The culprit code is in 

https://github.com/raphiniert-com/ra-data-postgrest/blob/master/src/index.ts#L189

https://github.com/raphiniert-com/ra-data-postgrest/blob/master/src/urlBuilder.ts#L241

## Possible solution

Fix the request to be like 

```
// GET http://127.0.0.1:54321/rest/v1/tags?id=in.()
```

But we don't even need to call the backend when the `ids` array is empty - we can return an empty response directly.

**Comment by scheiblr** [comment]
Thanks, I will look into it!
