### ISSUE TITLE
Allow to override nullsfirst / nullslast in getList sort

### ISSUE THREAD

**Issue by fzaninotto** [raphiniert-com/ra-data-postgrest#160]
## Problem

The `getList` implementation will use only `asc` or `desc` sort orders, while [PostgREST supports additional options](https://docs.postgrest.org/en/v12/references/api/tables_views.html#ordering) like `desc.nullslast`. 

There is no simple wat to set `nullsfirst` or `nullslast` in a `getList` query without overriding the entire `getList` implementation

## Solution

If the `getList` `meta` option contains `nullsfirst` or `nullslast`, append it to the sort order. 

```tsx
getList(
  'books',
  {
    pagination: { page: 1, perPage: 25 },
    sort: { field: 'published_at', order: 'DESC' },
  },
  { nullslast: true }
);
// GET /books?offset=0&limit=25&order=published_at.desc.nullslast
```

**Comment by scheiblr** [comment]
Thanks for stating this. I will look into this. Maybe, we could also implement it, so that it will be realizable by
```
getList(
  'books',
  {
    pagination: { page: 1, perPage: 25 },
    sort: { field: 'published_at', order: 'DESC.nullslast' },
  }
);
// GET /books?offset=0&limit=25&order=published_at.desc.nullslast
```

What do you think about that variant?

**Comment by fzaninotto** [comment]
Unfortunately, TypeScript won't let you do that as I think the `order` field is typed `'ASC' | 'DESC'`

**Comment by scheiblr** [comment]
I just saw in the code some mechanism for global setting: https://github.com/raphiniert-com/ra-data-postgrest?tab=readme-ov-file#null-sort-order

This is not an option for your use-case?

**Comment by fzaninotto** [comment]
in my use case, yes I think it can work. I still think this should be supported on a per-query basis.

**Comment by fzaninotto** [comment]
I tested the config and it doesn't work for `getList` (see #162)
