### ISSUE TITLE
Supabase returns an httperror on patch when values are equals

### ISSUE THREAD

**Issue by Revarh** [raphiniert-com/ra-data-postgrest#161]
Hello,

Working with supabase and react-admin, I sometimes find myself in the condition where I have a form updating data from either 1 or several tables are the same time, sometimes all together, sometimes separately.
When I update separately, part of the data remains unchanged but is still sent to supabase, which then returns an httperror:

`HttpError: JSON object requested, multiple (or no) rows returned`

For more precision here is a code example where I transform the data from a form:

```
const transform = (data, { previousData }) => {
  const transformedData = {
    ...data,
    name: toCamelCase(checkRightTypo(data.name)),
    phone: formatPhoneNumber(data.phone),
    email: getValidEmail(data.email),
    address: {
      street: toLowerCase(data.address?.street),
      postalCode: data.address?.postalCode,
      city: toLowerCase(data.address?.city),
    },
  }

  const copiedData = transformedData
  delete copiedData['@@ra-many/schools/school_exits/school_id']
  delete copiedData['@@ra-many/schools/school_interventions/school_id']
  delete copiedData['@@ra-many/schools/school_administrations/school_id']

  Object.keys(copiedData).forEach(key => {
    if ( key !== 'address' && copiedData[key] === previousData[key] ) {
      delete copiedData[key]
    }
  })

  if (
    copiedData['address'].street === previousData['address'].street &&
    copiedData['address'].postalCode === previousData['address'].postalCode &&
    copiedData['address'].city === previousData['address'].city
  ) {
    delete copiedData['address']
  }

  let finalData = {}
  if ( Object.keys(copiedData).length > 0 ) {
    finalData = {
      ...copiedData,
    }
  }

  finalData = {
    ['@@ra-many/schools/school_exits/school_id']: data['@@ra-many/schools/school_exits/school_id'],
    ['@@ra-many/schools/school_interventions/school_id']: data['@@ra-many/schools/school_interventions/school_id'],
    ['@@ra-many/schools/school_administrations/school_id']: data['@@ra-many/schools/school_administrations/school_id'],
    ...finalData,
  }

  return finalData
}
```

Here, previousData contains the data from a SimpleForm intererating with a table, for example here public.schools.

But using react-admin RA-many, I have a component in my SimpleForm which deals separately with another table, here public.school_streets.

When I change values solely in public.school_streets and then update my form, previousData still has my regular data (public.schools) and well as the date from ra-many, and thus inevitably compares this data with with I have in Supabase, resulting in the httpError.

Is there a way to make this httpError not happen, since it isn't really an error?

Thank you very much

**Comment by scheiblr** [comment]
Hi @Revarh,

thank you for bringing up you issue. However, I do not understand everything. First of all, are you using [marmelab/ra-supabase](https://github.com/marmelab/ra-supabase) or this particular data-provider?

Furthermore, I would be interested in the code of the form itself. Could you please post me some of that coce, at least a coarse sample of it?

**Comment by scheiblr** [comment]
Closing due to missing response. @Revarh feel free to reopen the issue.
