### ISSUE TITLE
Support Multiple APIs on Different Ports in React Admin Setup with PostgREST?

### ISSUE THREAD

**Issue by jnjaga24** [raphiniert-com/ra-data-postgrest#171]
I am working on a React Admin project where I need to connect to different databases, each running on a separate API and port. For example, one database runs on port 3000, while another runs on port 3001. The current setup uses PostgREST for data fetching, and I’m trying to configure it to support resources from different APIs (each with a distinct port) within the same React Admin instance.

The goal is to ensure that resources from different APIs (running on different ports) can be accessed simultaneously within the admin panel. However, I’m encountering issues when trying to load resources from multiple data providers. The configuration for the second data provider seems to be ignored, and the resource tab doesn’t appear in the UI.

Could you please provide guidance on how to properly set up React Admin to handle multiple APIs on different ports in the same instance?

`http://127.0.0.1:3000/user`
``http://127.0.0.1:3001/profile``
I need to render both list under same react admin UI.

I tried this, but no luck.

`<Admin dataProvider={dataProvider1}>
        <Resource name="user" list={userList} edit={userEdit}/>
<Admin dataProvider={dataProvider2}>
            <Resource name="profile" list={ListGuesser} edit={EditGuesser}/>
        </Admin>
    </Admin>`

**Comment by scheiblr** [comment]
Hey @jnjaga24 , thanks for the question. Personally, I would start [here](https://stackoverflow.com/questions/50724915/is-it-possible-to-have-multiple-dataproviders-in-react-admin) and potentially try one of the methods proposed. One answer mentioned a README.md in the ra-repo. Probably I would also look into that - just to see if something changed in RA4 now.

I hope this helps you! I would be interested how you end up realizing it!

Kind regards

**Comment by scheiblr** [comment]
Closing as most likely not an issue of this lib. @jnjaga24, feel free to open, if required. Also I would appreciate if you would share your solution and how you got it work.
