### ISSUE TITLE
custom port does not work

### ISSUE THREAD

**Issue by colonist4096** [raphiniert-com/ra-data-postgrest#2]
using postgrest

  server-host = "!4"
  server-port = 3001

and App.js

import postgrestRestProvider from 'ra-data-postgrest';
const dataProvider = postgrestRestProvider('http://localhost:3001');

gives index.js:1 Error: Network Error
    at createError (createError.js:16)
    at XMLHttpRequest.handleError (xhr.js:83)

when change posgrest to server-port = 80

it works

**Comment by scheiblr** [comment]
Are you writing a single page application? If so, I assume it to be an issue with CORS. Therefore, you would need to setup the frontend appropriately, e.g. create a proxy (e.g. documentation of [React](https://create-react-app.dev/docs/proxying-api-requests-in-development/#configuring-the-proxy-manually)).

**Comment by colonist4096** [comment]
Hello, thank you very much for looking into this.

 I am sorry issue was in my environent setup - instead of using your provider as a module i have copied it as a custom dataProvider (i need to extend it anyway) as a js file (because i have not installed ts and that was probably causing weirdness in my env) and everything works like a charm now..

 Thank you very much and sorry for irrelevant report
