### ISSUE TITLE
update method using incorrect source of id field

### ISSUE THREAD

**Issue by mkkane** [raphiniert-com/ra-data-postgrest#21]
Hi there, thank you for this library.

I just noticed that there is a small bug in the `update` method of the data-provider.  It is extracting the `id` from the `params.data` object -- but there is no guarantee this field will exist there.  This is also inconsistent with the other methods which all use `params.id` / `params.ids` -- as specified in the react-admin docs.

I've created a PR with a fix: https://github.com/raphiniert-com/ra-data-postgrest/pull/20

Hope that's ok!

**Comment by scheiblr** [comment]
Thank you very much and sorry for the delay. Just merged it and released a new version with your fix!
