### ISSUE TITLE
eq missing from single id lookup

### ISSUE THREAD

**Issue by andymed-jlp** [raphiniert-com/ra-data-postgrest#23]
Hi.

Firstly - thanks so much for this! Makes working with postgres a breeze!

With version 1.1.3 the single query URL ends with an ?id=eq.abc123 whereas in 1.1.5 it ends with ?id=abc123, and this causes an issue with my postgrest v7.0.1 instance. Am I doing something wrong?

If it's not me doing something stupid - I'm happy to work out the issue and do a PR!

Many Thanks,
Andy

**Comment by HR8981** [comment]
Hey Andy,

Just ran into the same issue myself.

Did you have any luck working this out? If not I'll see if l can work something out.

**Comment by andymed-jlp** [comment]
Hiya,

For the time being I just pinned to version 1.1.3 while I was working out if I'd just done something stupid. 

However I did take a look at the code and think I see the problem. So how I'll have a go this evening at fixing and making a PR? :-)

Cheers,
Andy

**Comment by scheiblr** [comment]
Are you calling rpc endpoints?

**Comment by andymed-jlp** [comment]
No, just a view.

**Comment by scheiblr** [comment]
Oh, then sorry for breaking it. I'm gonna digg into this issue asap.

**Comment by andymed-jlp** [comment]
No worries - these things happen :-) I think there may have been a piece of logic accidentally changed when the extra rpc logic was added. I've taken the liberty of creating a PR for the change - the change solves my particular issue.

**Comment by scheiblr** [comment]
Thanks a lot for the PR! This issue is fixed now in 1.1.6 :)
