### ISSUE TITLE
Any plans to add full text search?

### ISSUE THREAD

**Issue by Tanya301** [raphiniert-com/ra-data-postgrest#25]
Thank you for the library, very useful.

As I understand, now filtering support only LIKE type of search. It would be great to have full-text search too (`@@` operator in Postgres). Any plans for this?

**Comment by scheiblr** [comment]
Hey @Tanya301, excuse the late reply. Thank you for the question. This should already possible with the operators `fts`, `wfts`, `phfts` and `plfts` from postgrest (see [here](https://postgrest.org/en/stable/api.html#operators)). In combination with our [special filter feature](https://github.com/raphiniert-com/ra-data-postgrest#special-filter-feature) it should already work. If you have any issues, please don't hesitate to contact me again and reopen this issue.
