### ISSUE TITLE
Best way to use Compound key ?

### ISSUE THREAD

**Issue by TheRealAstroboy** [raphiniert-com/ra-data-postgrest#27]
It's not a issue, only a question : 
I'm using Compound key with ShowView but I'm not very proud of my code

```
const RowClick = (id, basePath, record) => {
	return `/myresource/${JSON.stringify([record.name,record.category] )}/show`;
}

const MyResourceList = (props) => (
	<List {...props}>
	   <Datagrid rowClick={RowClick}>
	    <TextField source="name" />
	  </Datagrid>
  </List>
);
```

Is there a better way to do it ? Any opinions would be greatly appreciated... :)

**Comment by TheRealAstroboy** [comment]
Ok, I got it, in my case, `rowClick='show'` is not working because my resource **MyResource** contains already an **id** field (that I don't want to use)...  😔

**Comment by scheiblr** [comment]
Thanks for pointing this out. That's for sure something I'll investigate further! Did you try to just remove the stated part of line 102?

**Comment by TheRealAstroboy** [comment]
@scheiblr I 'm gonna link a pull request to this issue but I need to test my code

```
const dataProviderRest= postgrestRestProvider(PG_URL, fetchUtils.fetchJson, 'eq', new Map([
        ['mytable',{'primaryKeys': ['name','zipcode'],'selectedFields':['name','department','city','zipcode','source']}],
]));
```
**selectedFields** allows you to include certain fields, either by passing an array (e.g. ['field1', 'field2'])
