### ISSUE TITLE
Update Fails on resources without primary keys named id

### ISSUE THREAD

**Issue by presentgokul** [raphiniert-com/ra-data-postgrest#28]
Consider a list which displays all brands , having columns (brand_name,brand_id<PK>), while updating the data below is the sample request body is getting fired to PostgRest

{
"brand_id":"88ed8a29-88ed-422e-8755-88ed577fa8be",
"brand_name":"Nike",
"id":"88ed8a29-88ed-422e-8755-88ed577fa8be"
}

Ideally the id shouldn't be present since this id column wont be available in db.

May be we should perform delete params.data.id while sending an update request

**Comment by scheiblr** [comment]
Thanks  for reporting the issue. Which request did you send? Am I understanding it right, that it was an update?
I need some more information in order to reproduce the issue.

**Comment by scheiblr** [comment]
feel free to reopen it, if I was wrong, but there seems no issue.
