### ISSUE TITLE
React Admin v4 does not work with current ra-data-postgrest version

### ISSUE THREAD

**Issue by promitheus7** [raphiniert-com/ra-data-postgrest#31]
When using `npm run build` with react-admin v4 and current version of `ra-data-postgrest` there is a build issue due to differing `ra-core` version usages. As a result, trying to compile using `npm run build` results in needing to use `react-admin v3.19` instead of the latest `v4.x`.

Two forks I've found that seem to have implemented this update - unsure about whether they work or not as my investigation has been quite superficial at this point. Hoping to spend some time this weekend testing version updates for myself to ensure functionality, and hopefully open a PR for updating dependencies to match `react-admin`.

https://github.com/Exact-Realty/ra-data-postgrest
https://github.com/milutinovici/ra-data-postgrest

EDIT: It seems there is currently a PR open as well with the version updates for `react-admin` compatibility when using `npm run build`: https://github.com/raphiniert-com/ra-data-postgrest/pull/30

**Comment by scheiblr** [comment]
@promitheus7, I would be very happy, if you could just push the changes upstream, instead of highjacking this project. Then I would create a new major version. That's how OS works generally. 

Kind regards

**Comment by promitheus7** [comment]
[PR](https://github.com/raphiniert-com/ra-data-postgrest/pull/33)

**Comment by scheiblr** [comment]
Hey @promitheus7, yeah, I was pretty bussy lately and still am ;) Sorry about that. I will look at it next week to clarify this and merge your PR. Thanks a lot for the contribution!
