### ISSUE TITLE
Enforce code formatting

### ISSUE THREAD

**Issue by christiaanwesterbeek** [raphiniert-com/ra-data-postgrest#40]
With my recent PR's I noticed code formatting is not enforced by something like prettier in this repo. I tried my best to format my changes to adhere to the current formatting, but it's not ideal. It makes for easier collaboration (and smaller PR's) if code formatting is enforced.

I propose to use prettier with the following .prettierrc config that adhere best to the current code formatting.

```
{
    "singleQuote": true,
    "tabWidth": 2,
    "trailingComma": "es5",
    "useTabs": false
}
```

**Comment by christiaanwesterbeek** [comment]
Or better even; Let's be on par with react-admin on code formatting and copy-paste there prettier config.

https://github.com/marmelab/react-admin/blob/master/.prettierrc.js

**Comment by scheiblr** [comment]
That is a great point. We should definitely do that. Currently, I'm pretty busy, I will invest some time, as soon as possible. Also, then I will check your PRs. I already coarsly looked into that, so please stay patient :)

**Comment by scheiblr** [comment]
added into branch `improvements`. This will be part of next release (which will probably still need some time). Thus, please stay patient ;) I will postpone your very valuable PRs, i.e. we have to incorporate them into the improved (future) version, once I made major progress with it.
