### ISSUE TITLE
needs screenshots in readme

### ISSUE THREAD

**Issue by wweevv-johndpope** [raphiniert-com/ra-data-postgrest#44]

**Comment by scheiblr** [comment]
Hey,

thanks for opening an issue.
Could you please clarify what you exactly mean? What kind of screenshots would you expect for such a piece of software?

Kind regards

**Comment by wweevv-johndpope** [comment]
what does
 <Admin dataProvider={postgrestRestProvider('http://path.to.my.api/')} 
           authProvider={authProvider}>
        <Resource name="posts" list={PostList} />
    </Admin> 
look like?

**Comment by scheiblr** [comment]
Well, that totally depend on the application and the component "PostList" one creates and relates to the end point "posts". I think this library, is more an abstract glue and I do not see the need for screenshots, although I totally see your perspective. In my opinion, this would rather be something for a use-case demo, which is not offered in the present repo. A demo as such would be an own project, which I currently do not intend to offer. I'm sorry, but out of my perspective, I would rather close this issue.

**Comment by wweevv-johndpope** [comment]
one thing I'm not clear on is pagination and if that's something offered here, or I have to build myself.
I can't read your mind. :(
