### ISSUE TITLE
Any plans to implement queryOptions?

### ISSUE THREAD

**Issue by DictumMortuum** [raphiniert-com/ra-data-postgrest#57]
https://marmelab.com/react-admin/List.html#queryoptions

**Comment by christiaanwesterbeek** [comment]
queryOptions are already passed as `meta` in  params to the dataProvider by RA itself.

Is there some specific kind of option that you are interested in passing with queryOptions/meta?

**Comment by DictumMortuum** [comment]
Not anything in particular - I was trying to pass a select to my List, but I couldn't figure out how, like this:

```<ListBase queryOptions={{ meta: {"select": "*,prices!inner(*)", "prices.store_id": "eq.6" }}}
```

**Comment by christiaanwesterbeek** [comment]
I'm working on that particular feature of filtering on columns (select param): #56

**Comment by scheiblr** [comment]
I think, that this feature should be available since v2.0.0-alpha.1. If I missed something, please reopen this issue.
