### ISSUE TITLE
Are embedded resources supported?

### ISSUE THREAD

**Issue by DictumMortuum** [raphiniert-com/ra-data-postgrest#58]
When I try to filter something on my List using this filter:

`filter={{ "name@ilike": "ticket"}}`

Everything works fine and a URL is generated like so: `&name=ilike.*ticket*`

When I try to filter the embedded resources, like so:

`filter={{ "prices.name@ilike": "ticket"}}`

It results in the following URL, which is correct: `&prices.name=ilike.*ticket*`

However when I try to implement the same filter using a TextInput, everything breaks down:

`<TextInput source="prices.name@ilike" label="search" />`

Results in: `prices=eq.%5Bobject+Object%5D`

**Comment by DictumMortuum** [comment]
Alright, did some investigation, it's due to the way react-admin passes the values to the data provider. The first examples are passed this way as params.filter:

`Object { "prices.name@ilike": "ticket" }`

Whereas in the latter case an object within an object is passed:

`Object { prices: {…} }`
​`prices: Object { "name@ilike": "ticket" }`

So right now I patched it on my own dataProvider by doing the following on parseFilters, however I'm not sure on the correct solution.

```
        let raw_key;
        let raw_val;
        if(isObject(filter[key])) {
            const [ inner ] = Object.keys(filter[key])
            raw_key = `${key}.${inner}`
            raw_val = filter[key][inner]
        } else {
            raw_key = key
            raw_val = filter[key]
        }
```

**Comment by scheiblr** [comment]
Thanks for reporting this. Feel free to contribute. I would recommend you, to first create a test case and then incorporate your patch. If the test case(s) pass, it should work out and you could contribute a pull request.

**Comment by scheiblr** [comment]
Hey @DictumMortuum, could you maybe give me more inside into this issue.
Best would be a minimal example, showing the expected way how it should work. Then, I would tackle that issue, soon.

**Comment by christiaanwesterbeek** [comment]
@DictumMortuum all our tests start from the dataProvider method params. So we don't really test how `<TextInput source="prices.name@ilike" label="search" />` creates a filter, but you discovered it does this:

> 
> Whereas in the latter case an object within an object is passed:
> 
> `Object { prices: {…} }`​`prices: Object { "name@ilike": "ticket" }`
> 

Using this info we can maybe track down what code in react-admin is detecting the dot in `prices.name` and decides to create a nested object. If we can import that code in a test case that creates this filter `{prices: { "name@ilike": "ticket" }}`, then we have a solid test case for an implementation that may very well look similar your patch.

**Comment by scheiblr** [comment]
Thank you very much. I do not exactely understand the connection of that RA issue. Do we need to extend something?
