### ISSUE TITLE
error with multiple delete

### ISSUE THREAD

**Issue by colonist4096** [raphiniert-com/ra-data-postgrest#7]
https://github.com/raphiniert-com/ra-data-postgrest/blob/c1677a84879d1517f71200dcbff2ad3e6b8cbc45/src/dataProvider/index.ts#L214

line change to 
`    }).then(({ json }) => ({ data: json.map(data => data.id) })),`
fixes it for me

**Comment by scheiblr** [comment]
Thank you! :)
