### ISSUE TITLE
Getting "Module not found" error

### ISSUE THREAD

**Issue by agrrd** [raphiniert-com/ra-data-postgrest#8]
Hi, when trying to use the package I am getting the following error:

```
Failed to compile.

./src/App.js
Module not found: Can't resolve '@raphiniert/ra-data-postgrest' in '/home/ag/git/rexample/admin/src'

```

Followed these steps:

```
$ npx create-react-app admin
$ cd admin
$ npm install react-admin  ra-data-json-server prop-types
$ npm install --save @raphiniert/ra-data-postgrest
```
The package is present in the node_modules directory:

```
$ pwd
/home/ag/git/rexample/admin

$ ls node_modules/@raphiniert/ra-data-postgrest/
CHANGELOG.md  LICENSE  node_modules  package.json  README.md  src
```

Then added the postgrestRestProvider line to the  ReactAdmin example in src/App.js:

```
import React from 'react';
import { Admin, Resource, ListGuesser } from 'react-admin';
import jsonServerProvider from 'ra-data-json-server';
import postgrestRestProvider from '@raphiniert/ra-data-postgrest';

const dataProvider = jsonServerProvider('https://jsonplaceholder.typicode.com');
const App = () => (
    <Admin dataProvider={dataProvider}>
        <Resource name="users" list={ListGuesser} />
    </Admin>
);

export default App
```

Nodejs version is v12.16.3

Any idea what I am missing? Sorry I have few experience in Nodejs and React.

**Comment by agrrd** [comment]
Found that for some reason my setup is not transpiling the .ts files to .js files when running the build target in the package.json

Got it working by manually running the following commands:

$  tsc --outDir lib --module commonjs src/index.ts src/dataProvider/index.ts src/authProvider/index.ts
$  tsc --outDir esm --module es2015 src/index.ts src/dataProvider/index.ts src/authProvider/index.ts

**Comment by olivierdalang** [comment]
Same issue here (with yarn), it would be nice to have this work out of the box if possible ? (not familiar with js packaging, but it seems other libraries don't require extra steps)

**Comment by olivierdalang** [comment]
For some unknown reason, I tried again with the above commands (`cd node_modules/@raphiniert/ra-data-postgres && npm install && npm run build`), and it now builds and works... Not sure what I did differently ?!

Anyways, if possible to package with the compiled JS, all the better !! Thanks :-)

**Comment by kdabir** [comment]
Looks like the published bundle does not include the js files. Any updates about next release? Currently not able to use the library :(

**Comment by scheiblr** [comment]
thanks for sharing the issue, I'm gonna fix this soon!

**Comment by scheiblr** [comment]
Should be fixed now. If you're still running into problems, please re-open! 
Thank you for opening this issue!
