### ISSUE TITLE
updateMany returns Bad Request Error

### ISSUE THREAD

**Issue by shazgames1** [raphiniert-com/ra-data-postgrest#88]
I'm using `ra-supabase` which uses this library under the hood. Whenever i call `updateMany` function, Supabase server returns 400 http error with response `{"code":"21000","details":null,"hint":null,"message":"UPDATE requires a WHERE clause"}`. I guess it's because to bulk update in postgrest we should pass ids into url params like this `id=in.(123,456,789)` instead of body

**Comment by scheiblr** [comment]
Thank you very much for raising this issue. Which postgREST version was used to raise that error?
I wonder, if we would get in trouble using the `in`-approach in case of compound keys. Maybe we should then call multiple single updates. What do you think about that @christiaanwesterbeek ?

**Comment by shazgames1** [comment]
As written in package.json of [ra-supabase-core](https://github.com/marmelab/ra-supabase/blob/main/packages/ra-supabase-core/package.json), it uses v2.0.0-alpha.0 of ra-data-postgrest

**Comment by scheiblr** [comment]
@shazgames1, I think you misunderstood something. I did not ask for the data provider's version, but the version of the postgREST version used underneath it (on serverside).

**Comment by shazgames1** [comment]
I don't know about Postgrest version Supabase uses. Know only postgres version: PostgreSQL 15.1 (Ubuntu 15.1-1.pgdg20.04+1) on aarch64-unknown-linux-gnu, compiled by gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0, 64-bit

**Comment by scheiblr** [comment]
Should be solved by new 2.0.0-alpha.4. You are invited to test it. I'll close that ticket. In case I missed something, please feel free to re-open the issue again.
