### ISSUE TITLE
how to implement full text filter?

### ISSUE THREAD

**Issue by jinguo-yin** [raphiniert-com/ra-data-postgrest#95]
in react-admin document, using 'q' in searchinput component to implement full text filter, how to do that in ra-data-postgrest?
thanks

**Comment by scheiblr** [comment]
I think this question is more a question of your application design and how you implemented the fulltext search inside the postgres db. If you are using zombodb, you would require to create a forward to the search endpoint and if you are using a builtin postgres fulltext feature you can use the postgrest opreators. This is possible with the [special-filter-feature](https://github.com/raphiniert-com/ra-data-postgrest#special-filter-feature).

**Comment by jinguo-yin** [comment]
@scheiblr Thanks, I'll try to use zombodb
